baseURL = 'https://dg-lee23.github.io/hugo-blog'
languageCode = 'en-us'
title = 'dStory'
theme = 'PaperMod'

[params]
    env = 'production'
    description = "ML/DL Research & Learning Process"
    author = "Donggyu Lee"
    defaultTheme = 'auto'
    
    # PROFILE MODE (The Landing Page)
    [params.profileMode]
        enabled = true
        title = "Hello! 👋"
        subtitle = "I'm Donggyu Lee, Undergraduate Student @ SNU.ECE"
        imageUrl = "profile_mine.png" # Link to a square photo
        [[params.profileMode.buttons]]
            name = "Blog Posts"
            url = "posts"
        [[params.profileMode.buttons]]
            name = "Personal Website"
            url = "https://dg-lee23.github.io/"

    # Social Icons
    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/dg-lee23"
    # [[params.socialIcons]]
    #    name = "googlescholar"
    #    url = "https://scholar.google.com/..."

[markup.goldmark.renderer]
    unsafe = true # Allows HTML in Markdown (useful for complex math/tables)

[markup.highlight]
    noClasses = false
    style = "monokai" # Good for Python/PyTorch code blocks